remote_theme: pages-themes/midnight@v0.2.0
url: https://machinetranslated.com
baseurl: ""
plugins:
- jekyll-remote-theme
- jekyll-sitemap
exclude:
- docs/translations/n0088hz/data.json
- docs/translations/n0088hz/en
- docs/translations/n0088hz/jp
- docs/translations/N5334EV/data.json
- docs/translations/N5334EV/en
- docs/translations/N5334EV/jp
- docs/translations/n4886hw/data.json
- docs/translations/n4886hw/en
- docs/translations/n4886hw/jp
- docs/translations/n7230gm/data.json
- docs/translations/n7230gm/en
- docs/translations/n7230gm/jp
- docs/translations/n3793gb/data.json
- docs/translations/n3793gb/en
- docs/translations/n3793gb/jp
- docs/translations/n5511kh/data.json
- docs/translations/n5511kh/en
- docs/translations/n5511kh/jp
